apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:brunocza/mba_usp-data_stack.git'
    path: infra/src/helm-charts/prometheus
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: monitorability
    server: ''
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
