apiVersion: v1
kind: Service
metadata:
  name: argocd-server-loadbalancer
  namespace: argocd
spec:
  type: LoadBalancer
  externalIPs:
    - "192.168.18.20"
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 81
      targetPort: 8080
