# Exemplo de secret para credenciais Git (HTTPS)
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: orchestrator
type: Opaque
data:
  # Para git-sync v4 (versão atual)
  GITSYNC_USERNAME: <base64_encoded_username>
  GITSYNC_PASSWORD: <base64_encoded_token_or_password>
  
---
# Como criar as credenciais base64:
# echo -n "seu_username" | base64
# echo -n "seu_github_token" | base64
