# Exemplo de secret para chave SSH
apiVersion: v1
kind: Secret
metadata:
  name: airflow-ssh-secret
  namespace: orchestrator
type: Opaque
data:
  # A chave precisa ter o nome 'gitSshKey'
  gitSshKey: <base64_encoded_private_key>
  
---
# Como criar a chave SSH base64:
# cat ~/.ssh/id_rsa | base64 -w 0
