apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: orchestrator
data:
  GIT_SYNC_USERNAME: YnJ1bm9jemE=
  GITSYNC_USERNAME: YnJ1bm9jemE=
  GIT_SYNC_PASSWORD: Z2hwX3VrVXRPdERHd3F1VU9sZU1TMUk4SFFxaXlDdlVwSTBaRmZPRA==
  GITSYNC_PASSWORD: Z2hwX3VrVXRPdERHd3F1VU9sZU1TMUk4SFFxaXlDdlVwSTBaRmZPRA==
