name: fhvhv_databricks
version: '1.0.0'
config-version: 2

profile: dbt_databricks

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fhvhv_databricks:
    bronze:
      +materialized: view
      +schema: bronze
      +tags: ["bronze"]
    silver:
      +materialized: table
      +schema: silver
      +tags: ["silver"]
    gold:
      +materialized: table
      +schema: gold
      +tags: ["gold"]
