apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: deepstorage
    server: ''
  source:
    path: infra/src/helm-charts/elasticsearch
    repoURL: 'git@github.com:brunocza/Data-Stack-K8s.git'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true


