apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: postgres-namespace
    server: ''
  source:
    path: infra/src/helm-charts/postgresql
    repoURL: 'git@github.com:brunocza/Data-Stack-K8s.git'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    # syncOptions:
    #   - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true


