apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:brunocza/mba_usp-data_stack.git'
    targetRevision: main
    path: infra/src/helm-charts/clickhouse/clickhouse
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    server: ''
    namespace: warehouse
  sources: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

